version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_USERNAME=bliss
      - MONGO_INITDB_PASSWORD=bliss
    volumes:
      - mongo-data:/data/db
    networks:
      - bliss

volumes:
  mongo-data:
networks:
  bliss:
    driver: bridge